In [47]:
# Numpy Numerical Python, Advanced lists help us store numbers effeciently , memory effecient, speedy

In [48]:
lst = [1, 2, 3, 4, 5]*10
print(lst)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [49]:
import time

In [50]:
# iterate

lst = [1,2,3,4,5]

start = time.time()
for i in range(len(lst)):
    a = lst[i]*10

print("\n time taken for list:", time.time() - start)




 time taken for list: 0.00041413307189941406


In [5]:
!pip install numpy

In [6]:
import numpy as np

a = [1, 2, 3, 4, 5]

b = np.array(a)

start = time.time()

new_b = b * 10

print("\n time taken for numpy array:", time.time() - start)



 time taken for numpy array: 0.00047969818115234375


In [7]:
# memory efficient

import sys

c = [1, 3, 5, 7, 9]

array = np.array(c)

print("c size:", sys.getsizeof(c))
print("array size:", array.nbytes)

c size: 104
array size: 40


In [8]:
# homogenous data

a = [1, "a", 4.5, True]
print(type(a))

arr = np.array(a)

arr

<class 'list'>


array(['1', 'a', '4.5', 'True'], dtype='<U32')

In [9]:
# numpy has many powerful tools which lists lack

np.array([2, 4, 6])

array([2, 4, 6])

In [10]:
# [34], 0 dimesions
# [45, 47, 87] # 1 dimension
# [1 2 3
# 4 5 6 ] # 2 dimensions

In [11]:
a1 = [1,2,3,4,5]

arr = np.array(a1)

arr.ndim


1

In [12]:
arr = np.array(34)
arr.ndim

0

In [13]:
# dimensions increase as the number of brackets increase

a = np.array([[[[[[[[]]]]]]]])

a.ndim

8

In [14]:
# shape of the array

arr.shape





()

In [15]:
# creation of array using built in functions

# for loop

l = [1,2]
a = np.array(l) 

In [16]:
# arange

a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [17]:
r = np.arange(1, 5, 2) 
r #start, stop, step

array([1, 3])

In [18]:
# linespace # evenly spaces 

arr = np.linspace(1, 5, 5)
arr # start , stop, no. of values

array([1., 2., 3., 4., 5.])

In [19]:
# log space # lograthmic space array # 2 points

arr = np.logspace(1, 3, 2)
arr

array([  10., 1000.])

In [20]:
# number of zeros

arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [21]:
arr = np.zeros([2, 5])
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
# numpy onw # where all values are 1

arr = np.ones([2,1])
arr

array([[1.],
       [1.]])

In [23]:
# an array full of that single value

arr = np.full([2, 4], 7.1)
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [24]:
# empty 

arr = np.empty([5,7])
arr  # nothing in it just for overide

array([[1.55807337e-311, 1.55806858e-311, 2.05833592e-312,
        2.41907520e-312, 2.56761491e-312, 2.16443571e-312,
        2.29175545e-312],
       [6.79038654e-313, 2.16443571e-312, 2.46151512e-312,
        2.05833592e-312, 6.79038654e-313, 2.22809558e-312,
        2.18565567e-312],
       [2.14321575e-312, 2.50395503e-312, 2.29175545e-312,
        2.14321575e-312, 2.12199579e-313, 2.41907520e-312,
        6.79038654e-313],
       [6.79038653e-313, 2.37663529e-312, 2.16443571e-312,
        2.29175545e-312, 8.48798317e-313, 1.06099790e-312,
        6.79038653e-313],
       [1.97345609e-312, 6.79038653e-313, 9.76118064e-313,
        8.70018275e-313, 2.05833592e-312, 2.41907520e-312,
        4.89124989e-322]])

In [25]:
# generating random

arr = np.random.rand(15)
arr

array([0.80325632, 0.20380493, 0.28246067, 0.26366576, 0.79582642,
       0.01503943, 0.44384403, 0.43419491, 0.29759541, 0.81079711,
       0.88059826, 0.34680766, 0.12682079, 0.2768064 , 0.23386724])

In [26]:
arr = np.random.rand(4, 5)
arr

array([[0.84809822, 0.15825221, 0.30629021, 0.91472947, 0.40018126],
       [0.84576405, 0.11254326, 0.9991081 , 0.58915438, 0.26604082],
       [0.20203434, 0.05364735, 0.07737297, 0.75453427, 0.11410977],
       [0.28872033, 0.52897821, 0.73292905, 0.83744708, 0.96952672]])

In [27]:
arr = np.random.randint(10,100)
arr

78

In [28]:
# data types in arrays

arr = np.array([1,2, 3, 4, 5])
arr.dtype

dtype('int64')

# int32 , int64 10,100, float32 3.14, float64 0.0009643, boolean, complex iota, string

In [29]:
# float into integer

arr = np.array([1.1, 2.1, 3.4], dtype = np.int64)
arr.dtype

dtype('int64')

In [30]:
# array
arr = np.array([[1,2,3],
                [4,5,6]])

In [31]:
arr.ndim


2

In [32]:
arr.shape

(2, 3)

In [33]:
arr.size # multiplying rows with columns

6

In [34]:
# array reshaping # through reshape, # ravel, # flatten\
    
# reshape

arr = np.array([1,3,5, 7,8,9])
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 3 5]
 [7 8 9]]


In [35]:
reshape2 = reshaped.reshape(3, 2)
print(reshape2)

[[1 3]
 [5 7]
 [8 9]]


In [36]:
# ravel

rave = reshape2.ravel()
rave
rave[0] = 100
print(rave)
print(reshape2)

[100   3   5   7   8   9]
[[100   3]
 [  5   7]
 [  8   9]]


In [37]:
# flatten  # converts into 1D array

flat = reshape2.flatten()
flat

flat[0] = 0
flat # only makes a copy








array([0, 3, 5, 7, 8, 9])

In [38]:
reshape2

array([[100,   3],
       [  5,   7],
       [  8,   9]])

In [39]:
# arithmetic operations

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [40]:
# addition

print(a + b)
# subtraction
print(b - a)

# multiply
print(a * b)

# division
print(a / b)

# modulus
print(a % b)

# exponent

print(a ** 2) # eulers number


[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[1 4 9]


In [41]:
# universal function in arrays
# ufuncs

arr = np.array([1, 6, 7])

# square root

print(np.sqrt(arr))

# exponential >np.exp x 

print(np.exp([1, 2]))

[1.         2.44948974 2.64575131]
[2.71828183 7.3890561 ]


In [42]:
# indexing slicing # under the umbrella of array

# slicing 

a = np.array([1, 2, 3, 4, 5])

print(a[-1:4])

print(a[0:4 :2])


[]
[1 3]


In [43]:
arr = np.array([10, 20, 30 , 40, 50])

print(arr[ : :2])

[10 30 50]


In [44]:
# negative indexing

print(arr[-4])



20


In [45]:
# multidimensional array

arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(arr2[0 :2, 0:3])

[[1 2 3]
 [4 5 6]]


In [46]:
# np.take function # prefered in indexing & slicing

arr = np.array([56, 78, 10, 100, 78, 99])

ind = [1, 4]

print(np.take(arr, ind))


[78 78]


In [51]:
# ITERATION IN ARRAYS
arra = np.array([[1,2], [3,4]])

for x in np.nditer(arra):
    print(x, end=" ")

1 2 3 4 

In [52]:
# ndenumerate , indexing + values

for index, value in np.ndenumerate(arra):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [54]:
# view and copy

arr = np.array([1, 2, 3, 8, 9])

view = arr.view()
view

array([1, 2, 3, 8, 9])

In [56]:
view[1] = 23
view
arr

array([ 1, 23,  3,  8,  9])

In [57]:
# copy

copy = arr.copy()
copy

array([ 1, 23,  3,  8,  9])

In [59]:
copy[1] = 46
copy
arr

array([ 1, 23,  3,  8,  9])

In [ ]:
# transpose # transpose of a matrix is changing row into column and column into row

mat = np.array([[3,5,7],
                [5,6,8]])
mat

array([[3, 5, 7],
       [5, 6, 8]])

In [62]:
print(mat.transpose())

[[3 5]
 [5 6]
 [7 8]]


In [65]:
# swap the axes of a matrix

mat.shape

swap = np.swapaxes(mat, 0, 1)
swap.shape

(3, 2)

In [67]:
mat.shape
swap

array([[3, 5],
       [5, 6],
       [7, 8]])

In [ ]:
# concatenate # not sum but combine

a = np.array([1,2])
b = np.array([3,4])

c = np.concatenate((a, b))
c

array([1, 2, 3, 4])

In [73]:
# stacking

xyz = np.array([[1, 2], [3, 4]])
abe = np.array([[5,6], [7,8]])

print(xyz)
print(abe)



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
# horizontal\\
    
sth = np.hstack((xyz, abe))
sth

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [72]:
# vertical

stv = np.vstack((xyz, abe))
stv

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [75]:
# splitting an array

arr1 = ([[1,2], [3,4], [5,6], [7,8]])
arr1

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [76]:
# splitting into two equal parts

print(np.array_split(arr1, 2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [77]:
# splitting into 3 parts
print(np.array_split(arr1, 3))

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [78]:
# repeating elements

arr = np.array([1,2,3])
print(np.repeat(arr, 4))

[1 1 1 1 2 2 2 2 3 3 3 3]


In [79]:
# tile > repeats whole array

print(np.tile(arr, 4))

[1 2 3 1 2 3 1 2 3 1 2 3]


In [80]:
# aggregate functions

arr = np.array([1,2,3,4,5])

print(np.sum(arr))

print(np.mean(arr))

print(np.std(arr)) # sqrt of variance

print(np.var(arr)) # variance is the spread from mean in any datasets

print(np.min(arr))
print(np.max(arr))

15
3.0
1.4142135623730951
2.0
1
5


In [81]:

mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [ ]:
print(np.sum(mat, axis=1)) # row wise addition 

print(np.sum(mat, axis=0)) # column wise addition

[ 6 15 24]
[12 15 18]


In [86]:
arr

array([1, 2, 3, 4, 5])

In [87]:
# cummulative operations

arr

print(np.cumsum(arr)) # cummulative sum

print(np.cumprod(arr)) # cummulative product

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [94]:
# condition bases choices

# where # it will return index or value where condition is true

arr

result = np.where(arr < 2, "low", "high")
result

array(['low', 'high', 'high', 'high', 'high'], dtype='<U4')

In [98]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
# argwhere # for rows and columns position in array

print(np.argwhere(arr < 2))


#mat 
print(np.argwhere(mat > 5))

[[0]]
[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [101]:
# and # when both conditions are true it will give me true

arr

print(np.logical_and(arr > 2, arr < 4))

[False False  True False False]


In [108]:
# or # when a single is true it will give true

print(np.logical_or(arr < 4, arr > 5))

[ True  True  True False False]


In [105]:
arr

array([1, 2, 3, 4, 5])

In [110]:
# boolean mask # selecting values based on true, false condition

mask = arr > 3
arr[mask]

array([4, 5])

In [113]:
# nonzero

arr4 = np.array([1,4,6,0,8,6,0,4])
print(np.nonzero(arr4))
print(arr4.nonzero())

(array([0, 1, 2, 4, 5, 7]),)
(array([0, 1, 2, 4, 5, 7]),)


In [115]:
# vectorizarion

# operations can directly be applied on numpy arrays 
# suppose i want to create a vectorize function np.vectorize 

def square(x):
    return x **2

In [116]:
vfunc = np.vectorize(square)

In [117]:
arr = np.array([1, 2, 3, 4, 5])
print(vfunc(arr))

[ 1  4  9 16 25]


In [ ]:
# handling missing values in a dataset
# nan not a number

# deal with missing values

a = np.array([1, 2, np.nan, 4, 5])
a

array([ 1.,  2., nan,  4.,  5.])

In [121]:
# .isinf # infinite


a

print(np.isnan(a))

[False False  True False False]


In [122]:
b = np.array([1,2,3, np.inf, np.nan, 5,9])

In [123]:
b


array([ 1.,  2.,  3., inf, nan,  5.,  9.])

In [125]:
# removing nan and infinites

new_b = np.nan_to_num(b)
new_b

array([1.00000000e+000, 2.00000000e+000, 3.00000000e+000, 1.79769313e+308,
       0.00000000e+000, 5.00000000e+000, 9.00000000e+000])

In [126]:
# saving an array

arr

array([1, 2, 3, 4, 5])

In [127]:
np.save('array.npy', arr)

In [128]:
# load

arr2 = np.load('array.npy')

In [129]:
arr2

array([1, 2, 3, 4, 5])